"use client"
import { Inter } from 'next/font/google'
import Footer from './Components/Footer/Footer'
import Navbar from './Components/Navbar/Navbar.jsx'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'NextUI',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
          {children}
        <Footer/>
      </body>
    </html>
  )
}
